name: Test 1

on:
  pull_request_review_comment:
    types: [created]

jobs:
  test:
    name: Test 1
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/gha run' && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association)
    timeout-minutes: 60
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 5
          submodules: true
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
#      - name: Rerun main workflow
        # Unfortunately, GitHub doesn't allow to rerun successful workflows via REST API:
        # https://stackoverflow.com/a/56684569
        # git tag tmp-rerun && git push --tags && git tag -d tmp-rerun && git push origin :tmp-rerun
#        run: |
#            git config --global user.name "GitHub Actions Bot"
#            git config --global user.email "bot@noreply.github.com"
#            git commit --allow-empty -m "trigger GitHub actions"
#            git push
#      - name: Rerun main workflow
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.WORKFLOW }}
#          repository: ${{ github.repository }}
#          event-type: manual-trigger
#          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - name: Test
        run: |
            sleep 30s
            exit -1
      - name: Send status
        if: ${{ always() }}
        run: |
            status="${{ job.status }}"
            status=${status/cancelled/failure}
            curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.WORKFLOW }}" \
              -d $(jq -n \
                --arg state $status \
                --arg url "${{ github.run_id }}" \
                --arg name "${{ github.workflow }}/${{ job.name }}" \
                '{"state":$state,"target_url":$url,"context":$name}') \
              "https://api.github.com/repos/microsoft/LightGBM/statuses/${{ github.event.pull_request.head.sha }}"
