name: Test 2

on:
  pull_request_review_comment:
    types: [created]

jobs:
  test:
    name: Test 2
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/gha run 2' && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association)
    timeout-minutes: 60
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: true
      - name: Send status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "pending" "${{ github.event.pull_request.head.sha }}"
      - name: Test
        run: |
            sleep 30s
            exit 0
      - name: Send status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "${{ job.status }}" "${{ github.event.pull_request.head.sha }}"
